name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - principal

jobs:
  build:
    uses: geode-sdk/build-geode-mod/.github/workflows/build.yml@v3
    with:
      sdk: v3.0.0
      combine: true
      
